language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yinhr/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true yinhr/react-docker yarn test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-858319333979"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
